---
title: "Programming & Processing"
subtitle: "How Will We Work in This Course?"
toc: true
date: 2026-08-27
---

## In-Class Agenda

- [ ] Discuss the assigned readings.
- [ ] Answer any questions about the Introduction to [Course Tools](../materials/introducing-defining-cad/01-CAD-tools.qmd).
- [ ] Start [Introduction to the Command Line & Prompt Engineering](../materials/introducing-defining-cad/02-intro-cli-prompt-engineering.qmd) and [Introduction to Versioning & Git](../materials/introducing-defining-cad/03-intro-versioning.qmd)(if not completed in-class, these will become homework).

## Assigned Materials

- Vincent, Nick, and Hanlin Li. “GitHub Copilot and the Exploitation of ‘Data Labor’: A Wake-Up Call for the Tech Industry.” *PSA Group* (blog), July 8, 2021. [https://www.psagroup.org/blogposts/101](https://www.psagroup.org/blogposts/101).
- Buschek, Christo, and Jer Thorp. “Models All The Way Down.” *Knowing Machines*. Accessed January 14, 2026. [https://knowingmachines.org/models-all-the-way](https://knowingmachines.org/models-all-the-way).
- Introduction to [Course Tools](../materials/introducing-defining-cad/01-CAD-tools.qmd)

## Additional Materials

- Chiang, Ted. “ChatGPT Is a Blurry JPEG of the Web.” *The New Yorker*, February 9, 2023. [https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web](https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web).
- Schaul, Kevin, Szu Yu Chen, and Nitasha Tiku. “Inside the Secret List of Websites That Make AI like ChatGPT Sound Smart.” *Washington Post*, April 19, 2023. [https://www.washingtonpost.com/technology/interactive/2023/ai-chatbot-learning/](https://www.washingtonpost.com/technology/interactive/2023/ai-chatbot-learning/).
