---
title: "Definitions & Disciplines"
subtitle: "What Is Culture As Data?"
toc: true
date: 2026-09-01
---

## In-Class Agenda

- [ ] Discuss assigned readings. Focus on questions of : what is culture as data? Where does it come from and who works with it? What does it mean to focus on cultural data versus other disciplinary approaches to data?
- [ ] Start discussing possible group themes and individual project ideas for the [semester-long project](../assessments/03-semester-project.qmd).

## Assigned Materials

- Manovich, Lev. “Types of Cultural Data.” In *Cultural Analytics*. MIT Press, 2020. [https://doi.org/10.7551/mitpress/11214.003.0009](https://doi.org/10.7551/mitpress/11214.003.0009).
- Posner, Miriam. “Humanities Data: A Necessary Contradiction – Miriam Posner’s Blog,” June 25, 2015. [https://miriamposner.com/blog/humanities-data-a-necessary-contradiction/](https://miriamposner.com/blog/humanities-data-a-necessary-contradiction/).

## Additional Materials

- Milligan, Ian. “The Transformation of Historical Research in the Digital Age.” *Elements in Historical Theory and Practice*, August 2022. [https://doi.org/10.1017/9781009026055](https://doi.org/10.1017/9781009026055).
- Liao, Zhehui, Maria Antoniak, Inyoung Cheong, et al. “LLMs as Research Tools: A Large Scale Survey of Researchers’ Usage and Perceptions.” arXiv:2411.05025. Preprint, arXiv, October 30, 2024. [https://doi.org/10.48550/arXiv.2411.05025](https://doi.org/10.48550/arXiv.2411.05025).

## Assignments

- Complete Initial Interest Survey (link available on Canvas) due by August 31 at midnight.
