---
title: "Version & File Histories"
subtitle: "How can we work collaboratively and computationally?"
toc: true
date: 2026-09-03
---

## In-Class Agenda

- [ ] Review Init IS310 Homework Questions & GitHub or Git related questions, discuss assigned readings
- [ ] Start introduction to File Formats. Slides available [here](../slides/04-version-file-histories.qmd){target="_blank"} and lesson available [here](../materials/introducing-defining-cad/06-intro-file-formats.qmd){target="_blank"}
- [ ] Time permitting first meeting of group project teams, discuss project ideas and potential datasets. Start working on your [collective and individual topic selection](../assessments/03-semester-project.qmd#milestone-1-collective--individual-topic-selection){target="_blank"}. Also get access to GitHub repositories for your group project, with the help of the instructors.

## Assigned Materials

- Chin, Monica. “Kids Who Grew up with Search Engines Could Change STEM Education Forever.” *The Verge*, September 22, 2021. [https://www.theverge.com/22684730/students-file-folder-directory-structure-education-gen-z](https://www.theverge.com/22684730/students-file-folder-directory-structure-education-gen-z){target="_blank"}.
- [Introduction to the Command Line & Prompt Engineering](../materials/introducing-defining-cad/02-intro-cli-prompt-engineering.qmd){target="_blank"}
- [Introduction to Versioning & Git](../materials/introducing-defining-cad/03-intro-versioning.qmd){target="_blank"}

## Additional Materials

- Ford, Paul. “What Is Code? If You Don’t Know, You Need to Read This.” *Bloomberg.Com*, June 11, 2015. [http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/](http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/){target="_blank"}.
- Namanyay Goel. “Vibe Coding Is a Dangerous Fantasy.” *N’s Blog*, March 20, 2025. [https://nmn.gl/blog/vibe-coding-fantasy](https://nmn.gl/blog/vibe-coding-fantasy){target="_blank"}.
- Weingart, Scott B. "The Route of a Text Message." *Vice*, February 2019. [https://www.vice.com/en_us/article/kzdn8n/the-route-of-a-text-message-a-love-story](https://www.vice.com/en_us/article/kzdn8n/the-route-of-a-text-message-a-love-story){target="_blank"}.

## Assignments

### Individual

- Complete [Init IS310 Homework](../materials/introducing-defining-cad/03-intro-versioning.qmd#homework-init-is310){target="_blank"}. **Be sure to include an AI chat log if you use AI!**

