---
title: "Histories of Culture & Computing"
subtitle: "How and when did we first start representing culture as data?"
toc: true
date: 2026-09-08
draft: true
---

## In-Class Agenda

- [ ] Discuss the assigned readings.
- [ ] Complete [Group Lab 1: Scholarship and Cultural Data Questions](../assessments/04-group-labs.qmd#group-lab-1-scholarship-and-cultural-data-questions).
- [ ] Time permitting work on topic selection and review [Advanced GitHub and Git Features for working collaboratively](../materials/introducing-defining-cad/05-advanced-git-github.qmd)

## Assigned Materials

- Kahle, Brewster. “Universal Access to All Knowledge.” *The American Archivist* 70, no. 1 (2007): 23–31. [https://doi.org/10.17723/aarc.70.1.u114006770252845](https://doi.org/10.17723/aarc.70.1.u114006770252845).
- Hennessey, Amardeep Singh and Kate. “African American Periodical Poetry (1900-1928) – *Responsible Datasets in Context*.” *Responsible Datasets in Context*, July 1, 2024. [https://www.responsible-datasets-in-context.com/posts/african-american-periodical-poetry/aa-periodical-poetry.html?tab=data-essay](https://www.responsible-datasets-in-context.com/posts/african-american-periodical-poetry/aa-periodical-poetry.html?tab=data-essay).
- Ding, Jennifer, Jan Diehm, and Michelle McGhee. “Can Data Die? Tracking the Lenna Image.” *The Pudding*, October 2021. [https://pudding.cool/2021/10/lenna](https://pudding.cool/2021/10/lenna).

## Additional Materials

- McPherson, Tara. “Why Are the Digital Humanities So White?: Or Thinking the Histories of Race and Computation.” In *Debates in the Digital Humanities*, edited by Matthew K. Gold, 139–60. University of Minnesota Press, 2012. [https://www.jstor.org/stable/10.5749/j.ctttv8hq.12](https://www.jstor.org/stable/10.5749/j.ctttv8hq.12).
- Besser, Howard. “The Past, Present, and Future of Digital Libraries.” In *A Companion to Digital Humanities*. John Wiley & Sons, Ltd, 2004. [https://doi.org/10.1002/9780470999875.ch36](https://doi.org/10.1002/9780470999875.ch36).
- Milic, Louis T. “The Next Step.” Computers and the Humanities 1, no. 1 (1966): 3–6. [http://www.jstor.org/stable/30199191](http://www.jstor.org/stable/30199191).

## Assignments

### Group

- [ ] [Group Lab 1: Scholarship and Cultural Data Questions](../assessments/04-group-labs.qmd#group-lab-1-scholarship-and-cultural-data-questions).
