---
title: "Markup & Markdown"
subtitle: "What does it mean to work digitally?"
toc: true
date: 2026-09-10
---

## In-Class Agenda

- [ ] Review [Lost & Found in the Cultural Command Line](../materials/introducing-defining-cad/06-intro-file-formats.qmd#homework-lost-found-in-the-cultural-command-line) and discuss assigned readings.
- [ ] Time Permitting start the [Introduction to Markup Languages & Web Styling](../materials/introducing-defining-cad/07-intro-html.qmd). Slides are available [here](../slides/06-intro-html-and-styling.qmd).

## Assigned Materials

- Things That Shouldn’t Be in File Names for $1,000 Alex – Joseph Scott. February 12, 2007. [https://blog.josephscott.org/2007/02/12/things-that-shouldnt-be-in-file-names-for-1000-alex/](https://blog.josephscott.org/2007/02/12/things-that-shouldnt-be-in-file-names-for-1000-alex/).
- Skim [Advanced Git & GitHub](../materials/introducing-defining-cad/05-advanced-git-github.qmd)
- Complete remainder of the [Introduction to File Formats](../materials/introducing-defining-cad/06-intro-file-formats.qmd) 

## Additional Materials

- Milligan, Ian. “Welcome to the Web: The Online Community of GeoCities during the Early Years of the World Wide Web.” In *The Web as History*, edited by Niels Brügger and Ralph Schroeder. University College London Press, 2017. [https://uwspace.uwaterloo.ca/handle/10012/11859](https://uwspace.uwaterloo.ca/handle/10012/11859).

## Assignments

### Individual

- [ ] [Lost & Found in the Cultural Command Line](../materials/introducing-defining-cad/06-intro-file-formats.qmd#homework-lost-found-in-the-cultural-command-line).

### Group

- [ ] [Proposal: Collective Focus and Individual Plan](../assessments/03-semester-project.qmd#milestone-1-proposal). Due **September 15, 2026** with automatic extension available until **September 22, 2026**.
