---
title: "Servers & Web Standards"
subtitle: "How has the web changed culture as data?"
toc: true
date: 2026-09-17
---

## In-Class Agenda

- [ ] Review the [Source & Style homework](../materials/introducing-defining-cad/07-intro-html.qmd#homework-source-and-style).
- [ ] Review the assigned lesson, slides are available [here](../slides/08-intro-web.qmd){target="_blank"}.
- [ ] Time permitting, develop the group's shared resources and website plans and update the [`group-work-log.md`](../assessments/02-weekly-assessments.qmd#group-collaboration-and-work-logs){target="_blank"}.

## Assigned Materials

- Read through the [Introduction to The Web & Servers](../materials/introducing-defining-cad/08-intro-web.qmd){target="_blank"} and come to class with questions.

## Additional Materials

- Veen, Jeffrey. “A Brief History of HTML | WIRED.” *Wired*, April 28, 1997. [https://www.wired.com/1997/04/a-brief-history-of-html/](https://www.wired.com/1997/04/a-brief-history-of-html/). 

## Assignments

### Individual

- [ ] [Source & Style Homework](../materials/introducing-defining-cad/07-intro-html.qmd#homework-source-and-style).

### Group
