---
title: "*Data Feminism* & Design Justice"
subtitle: "How do our choices shape whose culture becomes data?"
toc: true
date: 2026-09-22
---

## In-Class Agenda

- Discuss assigned readings
- Complete any remaining work on [Collective and Individual Topic Selection](../assessments/03-semester-project.qmd#milestone-1-collective-individual-topic-selection){target="_blank"} assignment.
- Start the [Mass Digitization, Digital Libraries, and Data Retirement](../assessments/06-collecting-digitizing-culture.qmd){target="_blank"} group assignment.

## Assigned Materials

- D’Ignazio, Catherine, and Lauren F. Klein. “The Power Chapter.” In *Data Feminism*. The MIT Press, 2020. [https://direct.mit.edu/books/oa-monograph/4660/chapter/213285/The-Power-Chapter](https://direct.mit.edu/books/oa-monograph/4660/chapter/213285/The-Power-Chapter){target="_blank"}. Also available on Canvas.
- D’Ignazio, Catherine, and Lauren F. Klein. “‘What Gets Counted Counts.’” In *Data Feminism*, by Catherine D’Ignazio and Lauren F. Klein. The MIT Press, 2020. [https://doi.org/10.7551/mitpress/11805.001.0001](https://doi.org/10.7551/mitpress/11805.001.0001){target="_blank"}. Also available on Canvas.
- Trejo, Sylvia Fernández and Paulina Hernandez. “Gender Violence at the Border (1993-1998) – *Responsible Datasets in Context*.” *Responsible Datasets in Context*, August 1, 2024. [https://www.responsible-datasets-in-context.com/posts/gender-violence/](https://www.responsible-datasets-in-context.com/posts/gender-violence/){target="_blank"}.

## Additional Materials

- Schimdt, Ben. “Gendered Language in Teaching Evaluations.” Accessed January 11, 2024. [https://benschmidt.org/profGender/](https://benschmidt.org/profGender/){target="_blank"}.
- Silge, Julia, Russell Samora, Amber Thomas, and Hanah Anderson. “She Giggles, He Gallops.” *The Pudding*, August 2017. [https://pudding.cool/2017/08/screen-direction](https://pudding.cool/2017/08/screen-direction){target="_blank"}.

## Assignments

### Individual

### Group

- [ ] [Collective and Individual Topic Selection](../assessments/03-semester-project.qmd#milestone-1-collective-individual-topic-selection){target="_blank"}. Final deadline!