---
title: "Scripts & Types"
subtitle: "How can we represent culture computationally?"
toc: true
date: 2026-09-24
---

## In-Class Agenda

- Discuss assigned readings from Tuesday, September 22, 2026.
- [ ] Review the [Doing It Live Homework](../materials/introducing-defining-cad/08-intro-web.qmd#assignment-doing-it-live) and discuss Python refresher materials.

## Assigned Materials

- Complete the [Python Refresher Part 1](../materials/creating-curating-cad/01-python-refresher-foundations.qmd) and [Python Refresher Part 2](../materials/creating-curating-cad/02-python-refresher-advanced.qmd).

As well as Tuesday's readings:

- D’Ignazio, Catherine, and Lauren F. Klein. “The Power Chapter.” In *Data Feminism*. The MIT Press, 2020. [https://direct.mit.edu/books/oa-monograph/4660/chapter/213285/The-Power-Chapter](https://direct.mit.edu/books/oa-monograph/4660/chapter/213285/The-Power-Chapter){target="_blank"}. Also available on Canvas.
- D’Ignazio, Catherine, and Lauren F. Klein. “‘What Gets Counted Counts.’” In *Data Feminism*, by Catherine D’Ignazio and Lauren F. Klein. The MIT Press, 2020. [https://doi.org/10.7551/mitpress/11805.001.0001](https://doi.org/10.7551/mitpress/11805.001.0001){target="_blank"}. Also available on Canvas.
- Trejo, Sylvia Fernández and Paulina Hernandez. “Gender Violence at the Border (1993-1998) – *Responsible Datasets in Context*.” *Responsible Datasets in Context*, August 1, 2024. [https://www.responsible-datasets-in-context.com/posts/gender-violence/](https://www.responsible-datasets-in-context.com/posts/gender-violence/){target="_blank"}.

## Assignments

### Individual

- [ ] [Doing It Live Homework](../materials/introducing-defining-cad/08-intro-web.qmd#assignment-doing-it-live).

### Group


