---
title: "Cleaning & Curating"
subtitle: "How do we decide which culture as data to capture?"
toc: true
date: 2026-09-29
---

## In-Class Agenda

- Discuss assigned readings
- Present the [Mass Digitization, Digital Libraries, and Data Retirement](../assessments/06-collecting-digitizing-culture.qmd){target="_blank"} group assignment.

## Assigned Materials

- Rawson, Katie, and Trevor Muñoz. “Against Cleaning.” In *Debates in the Digital Humanities 2019*, edited by Matthew K. Gold and Lauren F. Klein, 279–92. University of Minnesota Press, 2019. [https://doi.org/10.5749/j.ctvg251hk.26](https://doi.org/10.5749/j.ctvg251hk.26).
- Cegłowski, Maciej. “Deep-Fried Data.” *Idle Words*, September 27, 2016. [https://idlewords.com/talks/deep_fried_data.htm](https://idlewords.com/talks/deep_fried_data.htm).

Skim:

- Lurie, Stephen. “A History of Menus Is a Menu of History.” *The Pudding*, June 2026. [https://pudding.cool/2026/06/menu-story](https://pudding.cool/2026/06/menu-story).
- Daniels, Matt. “5,000 Restaurant Menus, Years 1880-1920.” *The Pudding*, June 2026. [https://pudding.cool/2026/06/menu-collection](https://pudding.cool/2026/06/menu-collection).

## Assignments

### Individual

### Group

- Start presentations for the [Mass Digitization, Digital Libraries, and Data Retirement](../assessments/06-collecting-digitizing-culture.qmd){target="_blank"} group assignment. Will complete remainder in the next Tuesday class session.
