---
title: "Terms & Traps"
subtitle: "Who has the right to represent and collect culture?"
toc: true
date: 2026-10-06
draft: true
---

## In-Class Agenda

- [ ] Discuss how we ethically and legally work with culture as data.
- [ ] Debate who has the right to represent, collect, circulate, and preserve culture.
- [ ] Complete [Group Lab 3: Finding Culture in Existing Datasets](../assessments/04-group-labs.qmd#group-lab-3-finding-culture-in-existing-datasets).

## Assigned Materials

- White, Sydney, Theo Serlin, Neel Gupta, and Kenneth Scheve. “A Historical Dataset of U.S. Governors.” *Responsible Datasets in Context*, February 2026. [https://www.responsible-datasets-in-context.com/posts/gubernatorial-bios/](https://www.responsible-datasets-in-context.com/posts/gubernatorial-bios/).
- Christen, Kimberly. “Does Information Really Want to Be Free? Indigenous Knowledge Systems and the Question of Openness.” *International Journal of Communication* 6 (November 30, 2012). [https://apo.org.au/node/265091](https://apo.org.au/node/265091).
- Lavigne, Sam. “Scrapism: A Manifesto.” *Critical AI* 1, no. 1–2 (October 1, 2023). [https://doi.org/10.1215/2834703X-10734046](https://doi.org/10.1215/2834703X-10734046).

## Assignments

### Group

- [ ] [Group Lab 3: Finding Culture in Existing Datasets](../assessments/04-group-labs.qmd#group-lab-3-finding-culture-in-existing-datasets).
