---
title: "Auditing & Archeology"
subtitle: "How can we contextualize culture as data?"
toc: true
date: 2026-10-20
draft: true
---

## In-Class Agenda

- Histories of data and data archeology
- Debate: What is the difference of auditing vs. creating data

## Assigned Materials

- Lee, Benjamin. “Compounded Mediation: A Data Archaeology of the Newspaper Navigator Dataset.” *Digital Humanities Quarterly* 15, no. 4 (2021). [https://digitalhumanities.org/dhq/vol/15/4/000578/000578.html](https://digitalhumanities.org/dhq/vol/15/4/000578/000578.html).
- Young, Liam Cole. “Film Box Office Charts and the Metadata of Culture.” In *Interrogating Datafication: Towards a Praxeology of Data*, edited by Marcus Burkhardt, Daniela van Geenen, Carolin Gerlitz, Sam Hind, Timo Kaerlein, Danny Lämmerhirt, and Axel Volmar, 61–82. Bielefeld: transcript Verlag, 2022. [https://doi.org/10.1515/9783839455616-003](https://doi.org/10.1515/9783839455616-003).

## Assignments

### Individual

- [ ] [Fandom Wikis and Web Scraping Homework](../materials/creating-curating-cad/05-web-scraping.qmd#fandom-wikis-and-web-scraping-homework)
- [ ] [Initial Custom Dataset and Audit Plan](../assessments/03-semester-project.qmd#milestone-2-initial-custom-dataset-and-audit-plan). Due today, with automatic extension available until October 27.

### Group
