---
title: "Automation & Algorithms"
subtitle: "How do we build trust with culture as data?"
toc: true
date: 2026-11-03
draft: true
---

## In-Class Agenda

- Algorithms & Trusting others to do the math
- limits of understanding technical details of computational methods vs understanding them based on how they work
- Debate: How much do we need to understand computational methods for using it to augment or create data? How can we understand the assumptions in these methods?

## Assigned Materials

- Luthra, Mrinalini, Konstantin Todorov, Charles Jeurgens, and Giovanni Colavizza. “Unsilencing Colonial Archives via Automated Entity Recognition.” *Journal of Documentation* 80, no. 5 (2024): 1080–105. [https://doi.org/10.1108/JD-02-2022-0038](https://doi.org/10.1108/JD-02-2022-0038).
- Schmidt, Benjamin M. “Do Digital Humanists Need to Understand Algorithms?” In *Debates in the Digital Humanities 2016*, edited by Matthew K. Gold and Lauren F. Klein, 546–55. University of Minnesota Press, 2016. [https://doi.org/10.5749/j.ctt1cn6thb.51](https://doi.org/10.5749/j.ctt1cn6thb.51).

## Assignments

### Individual

### Group
