---
title: 'Schedule & Assignments Overview'
toc: true
---

## Weekly Schedule

This overview gives a top level view of the topics for each of our meetings. You can either use the side navigation or click on a topic to jump to that section.

| Tuesday Topics (Explorations)  | Thursday Topics (Experimentations) |
| -----------------: | --------------: |
| [August 25 - Why Is This Not Called Computing in the Humanities? Introductions & Overviews](01-introductions-and-overviews.qmd) | [August 27 - How Will We Work in This Course? Programming & Processing](02-programming-and-processing.qmd) |
| [September 1 - What Is Culture As Data? Definitions & Disciplines](03-definitions-and-disciplines.qmd) | [September 3 - How can we work collaboratively and computationally? Version & File Histories](04-version-and-file-histories.qmd) |
| [September 8 - How and when did we first start representing culture as data? Histories of Culture & Computing](05-histories-of-culture-and-computing.qmd) | [September 10 - What does it mean to work digitally? Markup & Markdown](06-markup-and-markdown.qmd) |
<!--
| [September 15 - What are the historic legacies and politics of representing culture as data? Digital Objects & Obsolescence](07-digital-objects-and-obsolescence.qmd) | [September 17 - How has the web changed culture as data? Servers & Web Standards](08-servers-and-web-standards.qmd) |
| [September 22 - How do our choices shape whose culture becomes data? *Data Feminism* & Design Justice](09-data-feminism-and-design-justice.qmd) | [September 24 - How can we represent culture computationally? Scripts & Types](10-scripts-and-types.qmd) |
| [September 29 - How do we decide which culture as data to capture? Cleaning & Curating](11-cleaning-and-curating.qmd) | [October 1 - How can we start creating culture as data? Ecosystems & Environments](12-ecosystems-and-environments.qmd) |
| [October 6 - Who has the right to represent and collect culture? Terms & Traps](13-terms-and-traps.qmd) | [October 8 - How do we start scaling culture as data? Scrape On & Off](14-scrape-on-and-off.qmd) |
| [October 13 - What is infrastructure and how does it shape culture as data? Standards & Systems](15-standards-and-systems.qmd) | [October 15 - How do we get culture as data? Limits & Interfaces](16-limits-and-interfaces.qmd) |
| [October 20 - How can we contextualize culture as data? Auditing & Archeology](17-auditing-and-archeology.qmd) | [October 22 - How do we work at scale with culture as data? Patterns & Outliers](18-patterns-and-outliers.qmd) |
| [October 27 - How do we tell stories about culture with data? Arguments & Plots](19-arguments-and-plots.qmd) | [October 29 - How do we tell stories at scale? Scrolls & Hovers](20-scrolls-and-hovers.qmd) |
| [November 3 - How do we build trust with culture as data? Automation & Algorithms](21-automation-and-algorithms.qmd) | [November 5 - How can computation augment culture as data? Names & Texts](22-names-and-texts.qmd) |
| [November 10 - How are new technologies shaping culture as data? Augmentation & AI](23-augmentation-and-ai.qmd) | [November 12 - What does it mean to use computation critically for culture as data? Critical & Computational](24-critical-and-computational.qmd) |
| [November 17 - How can we preserve culture as data? Publics & Principles](25-publics-and-principles.qmd) | [November 19 - How do we document culture as data? Sheets & Sites](26-sheets-and-sites.qmd) |
| [December 1 - Is your dataset ready to share? Studio & Individual Projects](27-studio-and-individual-projects.qmd) | [December 3 - Is your website ready to launch? Studio & Group Projects](28-studio-and-group-projects.qmd) |
| [December 8 - What are the futures for culture as data? Presentations & Reflections](29-presentations-and-reflections.qmd) |  |
-->

## Assignment Schedule

*Assignments will be added throughout the semester depending on how much material we get through.*

### Individual Assignments

| Assignment | Due Date (Subject to Change) |
| -----------------: | --------------: |
| Initial Interest Survey (Link Available on Canvas) | [Due by Midnight CT on August 31](03-definitions-and-disciplines.qmd) |
| [Init IS310 Homework](../materials/introducing-defining-cad/03-intro-versioning.qmd#homework-init-is310) | [Due by Midnight CT on September 2](04-version-and-file-histories.qmd) |
[Lost & Found in the Cultural Command Line Homework](../materials/introducing-defining-cad/06-intro-file-formats.qmd#homework-lost-found-in-the-cultural-command-line) | [Due by Midnight CT on September 9](06-markup-and-markdown.qmd) |
<!-- 
| [Source & Style Homework](../materials/introducing-defining-cad/07-intro-html.qmd#homework-source-and-style) | [Due By Midnight CT on September 17](09-data-feminism-and-design-justice.qmd) |
| [Doing It Live Homework](../materials/introducing-defining-cad/08-intro-web.qmd#assignment-doing-it-live) | [Due By Midnight CT on September 24](11-cleaning-and-curating.qmd) |
|  -->

<!-- [OPTIONAL Scripting Python Foundations](../materials/creating-curating-cad/02-python-refresher-advanced.qmd#homework-scripting-python-foundations-optional-but-recommended) | [Due by Midnight CT on October 1](12-ecosystems-and-environments.qmd) |
| [Command Line Data Curation Homework](../materials/creating-curating-cad/04-virtual-environments.qmd#homework-command-line-data-curation) | [Due By Midnight CT on October 1](12-ecosystems-and-environments.qmd) |
| [Fandom Wikis and Web Scraping Homework](../materials/creating-curating-cad/05-web-scraping.qmd#fandom-wikis-and-web-scraping-homework) | [Due By Midnight CT on October 15](16-limits-and-interfaces.qmd) |
| [GETting Culture Across APIs Homework](../materials/creating-curating-cad/06-getting-data-apis.html#getting-culture-across-apis-homework) | [Due By Midnight CT on October 22](18-patterns-and-outliers.qmd) |
| [Exploring and Visualizing Culture Homework](../materials/augmenting-preserving-cad/02-eda-data-viz.qmd#exploring-and-visualizing-culture-homework) | [Due By Midnight CT on November 5](22-names-and-texts.qmd) | -->

### Group Assignments

| Assignment | Date |
| -----------------: | --------------: |
<!-- | [Group Lab 1: Scholarship and Cultural Data Questions](../assessments/04-group-labs.qmd#group-lab-1-scholarship-and-cultural-data-questions) | September 8 |
| [Proposal: Collective Focus and Individual Plan](../assessments/03-semester-project.qmd#milestone-1-collective-individual-topic-selection) | Due September 15 with automatic extension until September 22 |
| [Group Lab 2: From Cultural Object to Digital Representation](../assessments/04-group-labs.qmd#group-lab-2-from-cultural-object-to-digital-representation) | September 24 |
| [Group Lab 3: Finding Culture in Existing Datasets](../assessments/04-group-labs.qmd#group-lab-3-finding-culture-in-existing-datasets) | October 6 |
| [Initial Custom Dataset and Audit Plan](../assessments/03-semester-project.qmd#milestone-2-initial-custom-dataset-and-audit-plan) | Due October 20 with automatic extension until October 27 |
| [Group Lab 4: Augmenting Cultural Data with Computation](../assessments/04-group-labs.qmd#group-lab-4-augmenting-cultural-data-with-computation) | November 5 |
| [Final Group Presentation](../assessments/03-semester-project.qmd#milestone-3-final-group-presentation) | December 8 |
| [Final Project Submission](../assessments/03-semester-project.qmd#milestone-4-final-project-submission) | Due December 11 with optional extension until December 18 |

: Group lab and semester project schedule {tbl-colwidths="[60,40]" .striped .hover} -->
