---
title: "Assigned Project Groups"
toc: true
---

These project groups are based on the initial interest survey and are organized by course section.

::: {.callout-warning}
## Provisional Groups

These groups are provisional for the moment. They may change after remaining students submit the initial interest survey and after I review the finalized survey data.
:::

If you do not see your name listed, please complete the initial interest survey **as soon as possible**. If you have questions or concerns about your group placement, please contact the Instructor.

## Section A

### Group A1

**Suggested focus:** Popular & High Cultures: Film, television, visual culture, social media, and music/performance.

- Aashi A.
- Aidan L.
- Aadam P.
- Jack M.
- Sara J.

### Group A2

**Suggested focus:** Internet Cultures: Music, performance, film, television, sports, and visual culture.

- Aoife M.
- Rachel T.
- Hong J.
- Min K.
- Mazen A.

### Group A3

**Suggested focus:** Virtual Cultures: Social media, gaming, sports, film/television, and cultural history.

- Bob Z.
- Zilong F.
- Drew B.
- Mason L.


### Group A4

**Suggested focus:** Analytics & Culture: Sports analytics, film/television, gaming, and social media.

- Andres B.
- Pranay V.
- Jack G.
- Kingsley O.
- Gavin W.

## Section B

### Group B1

**Suggested focus:** Past Cultures: Music, performance, history, cultural heritage, literature, and environmentalism.

- Reva B.
- Chenglin C.
- Katie H.
- Aurora J.
- Anika P.

### Group B2

**Suggested focus:** Artistic Cultures: Art, music, film/television, and social media.

- Erin C.
- Vanisha N.
- Alina T.
- Fianna S.
- Zoe W.

### Group B3

**Suggested focus:** Gaming Cultures: Sports analytics, film and music, and gaming culture.

- Vedant P. 
- Yasir A.
- Brayden L.
- Eric T.
- Abhi P.

### Group B4

**Suggested focus:** Social Cultures: Sports and e-gaming, films, social media, and internet cultures.

- Britney O.
- Taylor B-M.
- Jaylin C.
- Ben T.
- Eric C.

### Group B5

**Suggested focus:** Academic Cultures: Academia, film and art, music, social media, and travel.

- Youngseo C.
- Shreya A.
- Silvia H.
- Cici Z.
- Tergel M.